### ISSUE TITLE
Cannot use object of type SmartEmailing\v3\Request\Import\Holder\ContactLists as array

### ISSUE THREAD

**Issue by MartkCz** [pionl/smart-emailing-v3#1]
https://github.com/pionl/smart-emailing-v3/blob/master/src/Request/Import/Contact.php#L385

version: v0.1.4

**Comment by pionl** [comment]
Hi @MartkCz, will fix in new version.

**Comment by pionl** [comment]
After more review, this API will be deprecated in near future. Please use the same concept as for custom fields:

```php
$contact->contactList()->add($list)
// or
$contact->contactList()->create('id', 'status')
```

**Comment by MartkCz** [comment]
Thanks!
