### ISSUE TITLE
Start using coding standard and strict types

### ISSUE THREAD

**Issue by stanislav-janu** [pionl/smart-emailing-v3#10]
Bylo by dobré začít používat nějaký coding standard a deklarování striktních typů. Kód je teď dosti zastaralý. Pokud na tom bude shoda, tak bych na tom začal dělat, ale nechci to dělat zbytečně.

Navrhuji použít https://github.com/nette/coding-standard

Souhlasí především @pionl?

**Comment by kubec** [comment]
Ano, kod by chtel trochu ucesat, pojdme to trochu vylepsit.

**Comment by pionl** [comment]
Souhlasím, nemám s tím problém. Osobně používám nyní používám jiný setup, ale nechám to klidně na Vás. PHPStan se nám teď osvědčil. 

Níže je setup pro phpcsfixer co interně používám na Laravel.

```
<?php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/app')
    ->in(__DIR__ . '/tests')
    ->in(__DIR__ . '/database')
    ->in(__DIR__ . '/routes')
    ->name('*.php')
    ->notName('*.blade.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PHP73Migration' => true,
        '@Symfony' => true,
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_superfluous_phpdoc_tags' => true,
        'yoda_style' => false,
        'concat_space' => ['spacing' => 'one'],
        'phpdoc_to_comment' => false,
    ))
    ->setFinder($finder);

```

**Comment by stanislav-janu** [comment]
Mě se na našich projektech osvědčilo používání Nette Code Standard (vychází z toho, že Nette používáme), Rector a PHPStan. Pokud bych tedy úpravu dělal já, tak na nette cs...

**Comment by pionl** [comment]
Ahoj @stanislav-janu, @keltuo 

navrhuji použít ECS a rector. používám nyní toto https://github.com/wrk-flow/larastrict/blob/main/ecs.php a https://github.com/wrk-flow/larastrict/blob/main/rector.php

Ale můžeme to "upravit" na nižší PHP verzi. Jakou chcete?

**Comment by stanislav-janu** [comment]
Pokud by všem vyhovovalo, nasadil bych to co používám u balíčku [janu-software/facebook-php-sdk](https://github.com/janu-software/facebook-php-sdk)

**Comment by pionl** [comment]
Osobně bych vynechal to NETTE_CODE_QUALITY ať je to není framework based (už tak to myslím ale má by default "symfony" code styles).

Já používám toto https://github.com/wrk-flow/larastrict/blob/main/rector.php + ecs bych nasadil (používám tot https://github.com/wrk-flow/larastrict/blob/main/ecs.php

**Comment by pionl** [comment]
nasazeno v rámci #24 :)
