### ISSUE TITLE
Remove changelog from readme

### ISSUE THREAD

**Issue by stanislav-janu** [pionl/smart-emailing-v3#12]
Odeberme z readme changelog, který beztak není udržovaný a nechme to na sekci s release na githubu.

**Comment by pionl** [comment]
Souhlasím, changelog už dávám do release

**Comment by stanislav-janu** [comment]
Pošlu pak PR.

**Comment by stanislav-janu** [comment]
PR #15

**Comment by pionl** [comment]
Díky mergnuto
