### ISSUE TITLE
Nové funkcionality

### ISSUE THREAD

**Issue by kubec** [pionl/smart-emailing-v3#13]
Dobry den,
muzu poprosit o pull request https://github.com/pionl/smart-emailing-v3/pull/8 ? 

Nechci zbytecne forkovat toto repo, byla by to skoda, at mame kod na 1 miste.

**Comment by pionl** [comment]
Mergnnuto, vypadá dobře, Díky

**Comment by pionl** [comment]
Přidáno jako `v0.3.0` 

cc @stanislav-janu
