### ISSUE TITLE
Dead package?

### ISSUE THREAD

**Issue by stanislav-janu** [pionl/smart-emailing-v3#14]
Chápu dobře, že je to tady další mrtvý balíček, protože původní vývojář @pionl nekomunikuje ani jednou za měsíc? Nechtěl by se toho balíčku spíše ujmout vývojáři ze Smart emailing?

**Comment by pionl** [comment]
Ahoj,
Tak určitě bych za to byl rád, můj čas se věnovat open source je minimální. Případně maintance můžu předat dál.

**Comment by stanislav-janu** [comment]
Chápu, že člověk má důležitější věci na práci, než open-source. Samozřejmě pokud tento balíček člověk potřebuje pro business, tak se mu i více věnuje. Takže to respektuji. 

Zajímalo by mě, zda-li by se správy balíčku ujmuli vývojáři přímo ze smartemailingu, jelikož pro ně je to důležitější.

**Comment by mstrouhal** [comment]
Ahoj, 
v průběhu roku vypustíme oficiálního API klienta pro PHP 7.4 / 8.0.

Dám pak vědět :-)

M.

**Comment by stanislav-janu** [comment]
> Ahoj,
> v průběhu roku vypustíme oficiálního API klienta pro PHP 7.4 / 8.0.
> 
> Dám pak vědět :-)
> 
> M.

To je ovšem velmi dobrá zpráva!! :-)
