### ISSUE TITLE
New feature in import double_opt_in_settings

### ISSUE THREAD

**Issue by james-fruhbauer** [pionl/smart-emailing-v3#17]
V Importu je v https://github.com/pionl/smart-emailing-v3/blob/master/src/Request/Import/Settings.php confirmation_request ale v dokumentaci neni a místo toho je tam double_opt_in_settings, bylo by potřeba upravit zápis a doplnit chybějící funkčnost.

**Comment by pionl** [comment]
Ahoj @james-fruhbauer, pokud máš prostor tak úprava je vítána.

**Comment by james-fruhbauer** [comment]
Tady jsem připravil PR https://github.com/pionl/smart-emailing-v3/pull/19, tak jestli na to můžete kouknout zda je to ok...

**Comment by pionl** [comment]
Zatím zde `v0.4.0-beta2`. Díky moc za změny
