### ISSUE TITLE
Minimální verze PHP

### ISSUE THREAD

**Issue by pionl** [pionl/smart-emailing-v3#23]
Jakou verzi PHP potřebujete podporovat? Bylo by fajn zahodit starší verze. Ale vidím dokonce instalaci na PHP. 5.6 😱 

Díky @stanislav-janu @james-fruhbauer @kubec @keltuo 

<img width="869" alt="Snímek obrazovky 2022-09-06 v 16 27 52" src="https://user-images.githubusercontent.com/1878831/188661578-3497863e-e57b-4934-8354-6f401e04ee72.png">

**Comment by stanislav-janu** [comment]
Osobně nepotřebuji cokoliv staršího  než 8.0

**Comment by stanislav-janu** [comment]
Starší software může použít starší verzi balíčku, ale pokud chci nové funkce, musím používat podporovanou verzi od php.net. Takže bych se řídil tím co je zelené na https://www.php.net/supported-versions.php

**Comment by pionl** [comment]
Souhlas, proto bych asi držel 7.4 jako min ještě nějakou chvilku a pak přejít na 8.

Osobně já nové projekty dělám čistě už jenom v 8.1.

**Comment by inDeev** [comment]
Prechod PHP 8.0 muze byt pro mnohe narocny kvuli podpore. Treba Microsoft na Azure Windows App Servisach dodnes netusi, ze PHP 8 existuje a dle prohlaseni jej ani neplanuje podporovat. Na Laravelu 8 je minimum ^7.3, asi bych to drzel. Vzhledem k tomu, ze balicek je momentalne dost odlehceny, nesazel bych na to, ze aktualni verze by byla pro majoritu PHP vyvojaru pouzitelna a jen ti s PHP ^8 by používali moduly, ktere by mely byt jiz v zakladu.

**Comment by pionl** [comment]
No to je dosti zajímavé :) Osobně v dnešní době kdy máme phpstan / rectorphp tak upgrady jsou snadnější než předtím...

Teoreticky můžeme udělat retorphp downgrade ale zatím se mi to nepodařilo udělat na jiném projektu.

**Comment by inDeev** [comment]
Minuly tyden jsem migroval vcelku velky projekt na PHP 8 a Laravel 9 - vse proslo bez problemu. Bohuzel az na nasazeni na Azure. Microsoft nezvlada PHP 8 ani na linuxovych servisach. Maji tam otevreny bug uz pres rok a nejak to neresi... https://github.com/microsoft/Oryx/issues/1100 . Predppokladam, ze spousta uzivatelu Laravelu se deli hlavne mezi Azure a AWS a jeden z nich bohuzel moderni technologie momentalne nezvlada...

**Comment by pionl** [comment]
[Tides has changed](https://packagist.org/packages/pion/smart-emailing-v3/php-stats) :)

- Koukal jsem a azure už PHP 8.0 umí :)
- Je docela šokující, že 7.4 vzrostla

Tak i tak, byl bych pro 8.0 a případně pokud přijdou issues tak udělat rector na downgrade a nějak vyřešit deploy jiné verze.

<img width="923" alt="Snímek obrazovky 2023-04-27 v 11 59 43" src="https://user-images.githubusercontent.com/1878831/234829276-84a29572-1fa8-4990-9a04-af6f23a224c7.png">

**Comment by pionl** [comment]
vyřešeno a rozhodnuto v #24
