### ISSUE TITLE
Padají testy na lowest dependencies

### ISSUE THREAD

**Issue by pionl** [pionl/smart-emailing-v3#33]
- opravil jsem běh testů na všech PHP verzích ale začalo to padat na testech při sběru code coverage

https://github.com/pionl/smart-emailing-v3/actions/runs/5422394046/jobs/9859004082 vs https://github.com/pionl/smart-emailing-v3/actions/runs/5422394046/jobs/9859004184

**Comment by MartinMystikJonas** [comment]
Opraveno zvednutím verze PHPUnit na minimálně 9.6 v #34
