### ISSUE TITLE
Undefined method importRequest()

### ISSUE THREAD

**Issue by tomasr1981** [pionl/smart-emailing-v3#36]
Hi,
something is missing? While using code from documentation:

```
use SmartEmailing\v3\Api;
$api = new Api('username', 'api-key');
$api->importRequest()->addContact(new Contact('test@test.cz'))->send();

```

I get an error about a missing method:

`Uncaught Error: Call to undefined method SmartEmailing\v3\Api::importRequest()`

**Comment by MartinMystikJonas** [comment]
It is weird. That method is there. What version do you have installed? It was nor present in older versions so maybe you somehow ended up with old version installed.

**Comment by tomasr1981** [comment]
Hi, I installed last version 0.4. But documentation is from new version (1)
which still is not on GIT.

**Comment by MartinMystikJonas** [comment]
Version 1.0 is still in pre-release but you can install it. Or use dev-master. 

@pionl Maybe you can publish v1.0 as full release already?

**Comment by tomasr1981** [comment]
I'm just pointing out the inconsistency.

**Documentation is related to 1.0 (importRequest() does not exists in 0.4)**
![Snímek obrazovky pořízený 2024-04-10 14-19-45](https://github.com/pionl/smart-emailing-v3/assets/41105085/2818552d-6d37-424b-aaad-503d1800104f)

**Latest realease is 0.4**

![Snímek obrazovky pořízený 2024-04-10 14-19-23](https://github.com/pionl/smart-emailing-v3/assets/41105085/b108f157-0aae-4c70-a5bb-ceac4a356d54)

**Comment by MartinMystikJonas** [comment]
README always point to latest dev version. 

Latest release is [v1.0.0-rc-2](https://github.com/pionl/smart-emailing-v3/releases/tag/v1.0.0-rc-2) but it is pre-release and GitHub shows latest stable release as latest.

**Comment by tomasr1981** [comment]
Ok, this is confusing. Composer installs 0.4, the readme shows 0.4, but the
documentation in the readme describes version 1.

**Comment by pionl** [comment]
sorry guys, I was waiting for the final confirmation.

Next time for RC I'll try to change the default branch to last stable release.

**Comment by pionl** [comment]
@tomasr1981 new version release, you can change the version to v1.0.0 - https://github.com/pionl/smart-emailing-v3/releases/tag/v1.0.0
